version: '3'
services:

#  gateway-service:
#    image: drugotosto84/gateway-service:1.0.0-SNAPSHOT
#    container_name: gateway-service
#    ports:
#      - "8080:8080"

#  zuul-service:
#    image: drugotosto84/zuul-service:1.0.0-SNAPSHOT
#    container_name: zuul-service
#    ports:
#      - "8080:8080"

  zookeeper:
    image: drugotosto84/kafka:2.0.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    entrypoint:
    - ./bin/zookeeper-server-start.sh
    command:
    - ./config/zookeeper.properties

  kafka:
    image: drugotosto84/kafka:2.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    entrypoint: ./bin/kafka-server-start.sh
    command:
      - config/server.properties
      - --override
      -   zookeeper.connect=zookeeper:2181
      - --override
      -   broker.id=0
      # unlike Kubernetes StatefulSet, compose gives containers a random hostname (leading to redirects to a hex name)
      - --override
      -   advertised.listener=PLAINTEXT://kafka:9092

  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    ports:
      - 9000:9000
    links:
      - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"

  ingestion-service:
    image: drugotosto84/ingestion-service:1.0.0-SNAPSHOT
    container_name: ingestion-service
    environment:
      SPRING_PROFILES_ACTIVE: "compose"
    ports:
      - "8080:8080"

  oee-comutation-service:
    image: drugotosto84/oee-computation-service:1.0.0-SNAPSHOT
    container_name: oee-comutation-service
    environment:
      SPRING_PROFILES_ACTIVE: "compose"
