version: '3'
services:

#  gateway-service:
#    image: drugotosto84/gateway-service:1.0.0-SNAPSHOT
#    container_name: gateway-service
#    ports:
#      - "8080:8080"
#    links:
#      - ingestion-service:ingestion-service

  kafkaserver:
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafkaserver
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafkaserver
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  ingestion-service:
    image: drugotosto84/ingestion-service:1.0.0-SNAPSHOT
    container_name: ingestion-service
    ports:
      - "8080:8080"
#    environment:
#      PROFILE: "default"

  oee-comutation-service:
      image: drugotosto84/oee-computation-service:1.0.0-SNAPSHOT
      container_name: oee-comutation-service