spring:
    application.name: ingestion-service
    cloud:
      stream:
        kafka:
          binder:
            brokers: kafkaserver:9092
        bindings:
          greetings-out:
            destination: greetings
            content-type: application/json

server:
  port: 8080
