spring:
  application:
    name: gateway

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

zuul:
  ignored-services: "*"
  routes:
    ingestion: 'orchestra/**'
    oee-computation: 'ssb/**'

