spring:
  application:
    name: gateway

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

zuul:
  ignored-services: "*"
#  prefix: "disloman-gateway/api/"
  routes:
    ingestion: 'orchestra/**'
    oee-computation: 'ssb/**'
#    ingestionservice:
#      path: 'orchestra/**'
#      serviceId: ingestion
#      stripPrefix: true
#    oeecomputationservice:
#      path: 'ssb/**'
#      serviceId: oee-computation
#      stripPrefix: true

