spring:
  application:
    name: gateway

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

zuul:
  prefix: "disloman-gateway/api/"
  ignored-services: "mongo, mongodns, zookeeper, zoodns"
  routes:
    ingestionservice:
      path: "orchestra/**"
      serviceId: "ingestion"
      stripPrefix: true
    oeecomputationservice:
      path: "ssb/**"
      serviceId: "oee-computation"
      stripPrefix: true

