spring:
  application.name: oee-computation-service
  profiles:
    active: default

# Kafka Configurations
  cloud:
    stream:
      bindings:
        greetings-in:
          destination: greetings
          content-type: application/json
          group: oee-Computation-Group
      kafka:
        binder:
          brokers: localhost:9092

# Mongodb Configurations
  data:
    mongodb:
      database: disloman
      uri: mongodb://localhost:27017/
#    # Spring DataRest Configuration
#    rest:
#      base-path: /ssb

server:
  port: 8080

---
spring:
  profiles: compose

# Kafka Configurations
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

# Mongodb Configurations
  data:
    mongodb:
      database: disloman
      uri: mongodb://mongo:27017/

---
spring:
  profiles: kub

  # Kafka Configurations
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

  # Mongodb Configurations
  data:
    mongodb:
      database: delete_me
      uri: mongodb://mongo:27017/



