spring:
  application:
    name: oee-computation

# Kafka Configurations
  cloud:
    stream:
      bindings:
        greetings-in:
          destination: greetings
          content-type: application/json
          group: oee-Computation-Group
      kafka:
        binder:
          brokers: kafka:9092

server:
  port: 8080

# Spring Boot Actuator "/health" endpoint configuration (Mostra dettagli aggiuntivi quando si ispeziona /health endpoint)
management:
  endpoint:
    health:
      show-details: always

# Spring Boot Actuator /info endpoint configuration (Informazioni customizzate da visualizzare quanto di ispeziona /info endpoint)
info:
  app:
    name: OeeComputation Micorservice
    description: Microservizio che si occupa di eseguire di calcolare l'OEE!

---
spring:
  profiles: compose

# Mongodb Configurations
  data:
    mongodb:
      database: disloman_docker
      uri: mongodb://mongo:27017/

---
spring:
  profiles: kub

  # Mongodb Configurations
  data:
    mongodb:
      database: disloman_kubernetes
      uri: mongodb://mongo:27017/



