spring:
  application.name: oee-computation-service
  profiles:
    active: default

server:
  port: 8080

# Kafka Configurations
  cloud:
    stream:
      bindings:
        greetings-in:
          destination: greetings
          content-type: application/json
          group: oee-Computation-Group
      kafka:
        binder:
          brokers: localhost:9092

# Mongodb Configurations
  data:
    mongodb:
      database: disloman
      uri: mongodb://localhost:27017/
#    # Spring DataRest Configuration
#    rest:
#      base-path: /ssb

# Spring Boot Actuator "/health" endpoint configuration (Mostra dettagli aggiuntivi quando si ispeziona /health endpoint)
management:
  endpoint:
    health:
      show-details: always

# Spring Boot Actuator /info endpoint configuration (Informazioni customizzate da visualizzare quanto di ispeziona /info endpoint)
info:
  app:
    name: OeeComputation Micorservice
    description: Microservizio che si occupa di eseguire di calcolare l'OEE!

---
spring:
  profiles: compose

# Kafka Configurations
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

# Mongodb Configurations
  data:
    mongodb:
      database: disloman
      uri: mongodb://mongo:27017/

---
spring:
  profiles: kub

  # Kafka Configurations
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

  # Mongodb Configurations
  data:
    mongodb:
      database: delete_me
      uri: mongodb://mongo:27017/



