spring:
  application.name: oee-computation-service
  profiles:
    active: compose

# Kafka Configurations
  cloud:
    stream:
      bindings:
        greetings-in:
          destination: greetings
          content-type: application/json
          group: oee-Computation-Group

server:
  port: 8080

---
spring:
  profiles: compose

# Kafka Configurations
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

---
spring:
  profiles: kub

  # Kafka Configurations
  cloud:
    stream:
      kafka:
        binder:
          brokers: bootstrap:9092




